name: "Stirling PDF"
version: "1.0.0"
slug: "stirling_pdf"
description: "Locally hosted PDF editor application."
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ports:
  8080/tcp: 8085
map:
  - type: data
    path: /configs
options: {}
schema: {}
